apiVersion: v1
kind: Service
metadata:
  name: portfolio-backend-service
  namespace: portfolio
  labels:
    app: portfolio-backend
spec:
  selector:
    app: portfolio-backend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
