# FastAPIの8080番ポートとつなぐ
upstream fastapi {
    # サーバにFastAPIのコンテナ名を指定。app_python311
    # ポートはFastAPIのコンテナの8080番Port
    server portfolio:8080;
}

server {
    # HTTPの80番Portを指定
    # コンテナのnginxのportと合わせる
    listen 80;
    server_name 0.0.0.0;

    # プロキシ設定
    # 実際はNginxのコンテナにアクセスしてるのをFastAPIにアクセスしてるかのようにみせる
    location / {
        proxy_pass http://fastapi;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
    }
}
