# FastAPIの8080番ポートとつなぐ
upstream fastapi {
    # サーバにFastAPIのコンテナ名を指定。app_python311
    # ポートはFastAPIのコンテナの8080番Port
    server portfolio:8080;
}

server {
    # HTTPの80番Portを指定
    # コンテナのnginxのportと合わせる
    listen 443 ssl;
    server_name 0.0.0.0;

    # SSL証明書の設定
    ssl_certificate /etc/ssl/server.crt;
    ssl_certificate_key /etc/ssl/server.key;
    ssl_password_file /etc/ssl/server.password;

    # プロキシ設定
    # 実際はNginxのコンテナにアクセスしてるのをFastAPIにアクセスしてるかのようにみせる
    location / {
        proxy_pass http://fastapi;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
    }
}
