apiVersion: v1
kind: Service
metadata:
  name: portfolio-frontend-service
  namespace: portfolio
  labels:
    app: portfolio-frontend
spec:
  selector:
    app: portfolio-frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
